# volumes:

services:
  app:
    build:
      context: backend
    container_name: volleyball_scorer_app
    environment:
      - APP_PORT=${APP_PORT}
    # volumes:
      # - db_backup:db_backup

  nginx:
    image: nginx:alpine
    container_name: volleyball_scorer_nginx
    ports:
      - "80:80"
    volumes:
      # Option A: replace the entire nginx.conf (requires events {} and http {} wrappers in the file)
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # Option B: only override the server block, letting the default nginx.conf handle the http {} wrapper
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - APP_ADDR=app:${APP_PORT}
    depends_on:
      - app

  ngrok:
    image: ngrok/ngrok
    container_name: volleyball_score_ngrok
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok/ngrok.yml
    ports:
      - 4040:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN} 
    command: "start --all --config /etc/ngrok/ngrok.yml"
    depends_on:
      - nginx
