#!/usr/bin/env bash

# CREATES THE READER USERS, IT'S BASH TO USE ENV VARS
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_NEW_USER WITH LOGIN PASSWORD '$POSTGRES_NEW_PASSWORD';
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_NEW_USER;
EOSQL

